[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production"
PORT = "3000"
